/* Autogenerated by vararg_c */

int
TIFFSetField_TIFFTAG_ARTIST (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_ARTIST, arg1);
}

char*
TIFFGetField_TIFFTAG_ARTIST (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_ARTIST, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_BADFAXLINES (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_BADFAXLINES, arg1);
}

uint32
TIFFGetField_TIFFTAG_BADFAXLINES (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_BADFAXLINES, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_BITSPERSAMPLE (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_BITSPERSAMPLE, arg1);
}

uint16
TIFFGetField_TIFFTAG_BITSPERSAMPLE (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_BITSPERSAMPLE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_CLEANFAXDATA (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_CLEANFAXDATA, arg1);
}

uint16
TIFFGetField_TIFFTAG_CLEANFAXDATA (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_CLEANFAXDATA, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_COMPRESSION (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_COMPRESSION, arg1);
}

uint16
TIFFGetField_TIFFTAG_COMPRESSION (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_COMPRESSION, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_CONSECUTIVEBADFAXLINES (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_CONSECUTIVEBADFAXLINES, arg1);
}

uint32
TIFFGetField_TIFFTAG_CONSECUTIVEBADFAXLINES (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_CONSECUTIVEBADFAXLINES, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_COPYRIGHT (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_COPYRIGHT, arg1);
}

char*
TIFFGetField_TIFFTAG_COPYRIGHT (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_COPYRIGHT, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_DATETIME (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_DATETIME, arg1);
}

char*
TIFFGetField_TIFFTAG_DATETIME (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_DATETIME, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_DOCUMENTNAME (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_DOCUMENTNAME, arg1);
}

char*
TIFFGetField_TIFFTAG_DOCUMENTNAME (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_DOCUMENTNAME, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_FAXMODE (TIFF* tif, int arg1)
{
  return TIFFSetField (tif, TIFFTAG_FAXMODE, arg1);
}

int
TIFFGetField_TIFFTAG_FAXMODE (TIFF* tif)
{
  int arg1;

  TIFFGetField (tif, TIFFTAG_FAXMODE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_FILLORDER (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_FILLORDER, arg1);
}

uint16
TIFFGetField_TIFFTAG_FILLORDER (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_FILLORDER, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_GROUP3OPTIONS (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_GROUP3OPTIONS, arg1);
}

uint32
TIFFGetField_TIFFTAG_GROUP3OPTIONS (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_GROUP3OPTIONS, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_GROUP4OPTIONS (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_GROUP4OPTIONS, arg1);
}

uint32
TIFFGetField_TIFFTAG_GROUP4OPTIONS (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_GROUP4OPTIONS, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_HOSTCOMPUTER (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_HOSTCOMPUTER, arg1);
}

char*
TIFFGetField_TIFFTAG_HOSTCOMPUTER (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_HOSTCOMPUTER, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_IMAGEDESCRIPTION (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_IMAGEDESCRIPTION, arg1);
}

char*
TIFFGetField_TIFFTAG_IMAGEDESCRIPTION (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_IMAGEDESCRIPTION, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_IMAGEDEPTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_IMAGEDEPTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_IMAGEDEPTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_IMAGEDEPTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_IMAGELENGTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_IMAGELENGTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_IMAGELENGTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_IMAGELENGTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_IMAGEWIDTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_IMAGEWIDTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_IMAGEWIDTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_IMAGEWIDTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_INKNAMES (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_INKNAMES, arg1);
}

char*
TIFFGetField_TIFFTAG_INKNAMES (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_INKNAMES, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_INKSET (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_INKSET, arg1);
}

uint16
TIFFGetField_TIFFTAG_INKSET (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_INKSET, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_JPEGQUALITY (TIFF* tif, int arg1)
{
  return TIFFSetField (tif, TIFFTAG_JPEGQUALITY, arg1);
}

int
TIFFGetField_TIFFTAG_JPEGQUALITY (TIFF* tif)
{
  int arg1;

  TIFFGetField (tif, TIFFTAG_JPEGQUALITY, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_JPEGCOLORMODE (TIFF* tif, int arg1)
{
  return TIFFSetField (tif, TIFFTAG_JPEGCOLORMODE, arg1);
}

int
TIFFGetField_TIFFTAG_JPEGCOLORMODE (TIFF* tif)
{
  int arg1;

  TIFFGetField (tif, TIFFTAG_JPEGCOLORMODE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_JPEGTABLESMODE (TIFF* tif, int arg1)
{
  return TIFFSetField (tif, TIFFTAG_JPEGTABLESMODE, arg1);
}

int
TIFFGetField_TIFFTAG_JPEGTABLESMODE (TIFF* tif)
{
  int arg1;

  TIFFGetField (tif, TIFFTAG_JPEGTABLESMODE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_MAKE (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_MAKE, arg1);
}

char*
TIFFGetField_TIFFTAG_MAKE (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_MAKE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_MATTEING (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_MATTEING, arg1);
}

uint16
TIFFGetField_TIFFTAG_MATTEING (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_MATTEING, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_MAXSAMPLEVALUE (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_MAXSAMPLEVALUE, arg1);
}

uint16
TIFFGetField_TIFFTAG_MAXSAMPLEVALUE (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_MAXSAMPLEVALUE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_MINSAMPLEVALUE (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_MINSAMPLEVALUE, arg1);
}

uint16
TIFFGetField_TIFFTAG_MINSAMPLEVALUE (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_MINSAMPLEVALUE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_MODEL (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_MODEL, arg1);
}

char*
TIFFGetField_TIFFTAG_MODEL (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_MODEL, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_ORIENTATION (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_ORIENTATION, arg1);
}

uint16
TIFFGetField_TIFFTAG_ORIENTATION (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_ORIENTATION, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_PAGENAME (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_PAGENAME, arg1);
}

char*
TIFFGetField_TIFFTAG_PAGENAME (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_PAGENAME, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_PHOTOMETRIC (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_PHOTOMETRIC, arg1);
}

uint16
TIFFGetField_TIFFTAG_PHOTOMETRIC (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_PHOTOMETRIC, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_PLANARCONFIG (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_PLANARCONFIG, arg1);
}

uint16
TIFFGetField_TIFFTAG_PLANARCONFIG (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_PLANARCONFIG, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_PREDICTOR (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_PREDICTOR, arg1);
}

uint16
TIFFGetField_TIFFTAG_PREDICTOR (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_PREDICTOR, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_PRIMARYCHROMATICITIES (TIFF* tif, float* arg1)
{
  return TIFFSetField (tif, TIFFTAG_PRIMARYCHROMATICITIES, arg1);
}

float*
TIFFGetField_TIFFTAG_PRIMARYCHROMATICITIES (TIFF* tif)
{
  float* arg1;

  TIFFGetField (tif, TIFFTAG_PRIMARYCHROMATICITIES, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_REFERENCEBLACKWHITE (TIFF* tif, float* arg1)
{
  return TIFFSetField (tif, TIFFTAG_REFERENCEBLACKWHITE, arg1);
}

float*
TIFFGetField_TIFFTAG_REFERENCEBLACKWHITE (TIFF* tif)
{
  float* arg1;

  TIFFGetField (tif, TIFFTAG_REFERENCEBLACKWHITE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_RESOLUTIONUNIT (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_RESOLUTIONUNIT, arg1);
}

uint16
TIFFGetField_TIFFTAG_RESOLUTIONUNIT (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_RESOLUTIONUNIT, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_ROWSPERSTRIP (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_ROWSPERSTRIP, arg1);
}

uint32
TIFFGetField_TIFFTAG_ROWSPERSTRIP (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_ROWSPERSTRIP, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SAMPLEFORMAT (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_SAMPLEFORMAT, arg1);
}

uint16
TIFFGetField_TIFFTAG_SAMPLEFORMAT (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_SAMPLEFORMAT, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SAMPLESPERPIXEL (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_SAMPLESPERPIXEL, arg1);
}

uint16
TIFFGetField_TIFFTAG_SAMPLESPERPIXEL (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_SAMPLESPERPIXEL, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SMAXSAMPLEVALUE (TIFF* tif, double arg1)
{
  return TIFFSetField (tif, TIFFTAG_SMAXSAMPLEVALUE, arg1);
}

double
TIFFGetField_TIFFTAG_SMAXSAMPLEVALUE (TIFF* tif)
{
  double arg1;

  TIFFGetField (tif, TIFFTAG_SMAXSAMPLEVALUE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SMINSAMPLEVALUE (TIFF* tif, double arg1)
{
  return TIFFSetField (tif, TIFFTAG_SMINSAMPLEVALUE, arg1);
}

double
TIFFGetField_TIFFTAG_SMINSAMPLEVALUE (TIFF* tif)
{
  double arg1;

  TIFFGetField (tif, TIFFTAG_SMINSAMPLEVALUE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SOFTWARE (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_SOFTWARE, arg1);
}

char*
TIFFGetField_TIFFTAG_SOFTWARE (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_SOFTWARE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_STONITS (TIFF* tif, double arg1)
{
  return TIFFSetField (tif, TIFFTAG_STONITS, arg1);
}

double
TIFFGetField_TIFFTAG_STONITS (TIFF* tif)
{
  double arg1;

  TIFFGetField (tif, TIFFTAG_STONITS, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_SUBFILETYPE (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_SUBFILETYPE, arg1);
}

uint32
TIFFGetField_TIFFTAG_SUBFILETYPE (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_SUBFILETYPE, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_TARGETPRINTER (TIFF* tif, char* arg1)
{
  return TIFFSetField (tif, TIFFTAG_TARGETPRINTER, arg1);
}

char*
TIFFGetField_TIFFTAG_TARGETPRINTER (TIFF* tif)
{
  char* arg1;

  TIFFGetField (tif, TIFFTAG_TARGETPRINTER, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_THRESHHOLDING (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_THRESHHOLDING, arg1);
}

uint16
TIFFGetField_TIFFTAG_THRESHHOLDING (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_THRESHHOLDING, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_TILEDEPTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_TILEDEPTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_TILEDEPTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_TILEDEPTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_TILELENGTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_TILELENGTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_TILELENGTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_TILELENGTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_TILEWIDTH (TIFF* tif, uint32 arg1)
{
  return TIFFSetField (tif, TIFFTAG_TILEWIDTH, arg1);
}

uint32
TIFFGetField_TIFFTAG_TILEWIDTH (TIFF* tif)
{
  uint32 arg1;

  TIFFGetField (tif, TIFFTAG_TILEWIDTH, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_XRESOLUTION (TIFF* tif, float arg1)
{
  return TIFFSetField (tif, TIFFTAG_XRESOLUTION, arg1);
}

float
TIFFGetField_TIFFTAG_XRESOLUTION (TIFF* tif)
{
  float arg1;

  TIFFGetField (tif, TIFFTAG_XRESOLUTION, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_WHITEPOINT (TIFF* tif, float* arg1)
{
  return TIFFSetField (tif, TIFFTAG_WHITEPOINT, arg1);
}

float*
TIFFGetField_TIFFTAG_WHITEPOINT (TIFF* tif)
{
  float* arg1;

  TIFFGetField (tif, TIFFTAG_WHITEPOINT, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_YCBCRCOEFFICIENTS (TIFF* tif, float* arg1)
{
  return TIFFSetField (tif, TIFFTAG_YCBCRCOEFFICIENTS, arg1);
}

float*
TIFFGetField_TIFFTAG_YCBCRCOEFFICIENTS (TIFF* tif)
{
  float* arg1;

  TIFFGetField (tif, TIFFTAG_YCBCRCOEFFICIENTS, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_YCBCRPOSITIONING (TIFF* tif, uint16 arg1)
{
  return TIFFSetField (tif, TIFFTAG_YCBCRPOSITIONING, arg1);
}

uint16
TIFFGetField_TIFFTAG_YCBCRPOSITIONING (TIFF* tif)
{
  uint16 arg1;

  TIFFGetField (tif, TIFFTAG_YCBCRPOSITIONING, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_YPOSITION (TIFF* tif, float arg1)
{
  return TIFFSetField (tif, TIFFTAG_YPOSITION, arg1);
}

float
TIFFGetField_TIFFTAG_YPOSITION (TIFF* tif)
{
  float arg1;

  TIFFGetField (tif, TIFFTAG_YPOSITION, &arg1);

  return arg1;
}

int
TIFFSetField_TIFFTAG_YRESOLUTION (TIFF* tif, float arg1)
{
  return TIFFSetField (tif, TIFFTAG_YRESOLUTION, arg1);
}

float
TIFFGetField_TIFFTAG_YRESOLUTION (TIFF* tif)
{
  float arg1;

  TIFFGetField (tif, TIFFTAG_YRESOLUTION, &arg1);

  return arg1;
}

